GET http://localhost:8080/usuario
###
GET http://localhost:8080/usuario/32
###
POST http://localhost:8080/usuario
Content-Type: application/json
Accept: application/json

{
  "nombre_usuario": "veterinario1",
  "contrasena": "veterinario11"
}
###
GET http://localhost:8080/tips
###
GET http://localhost:8080/tips/7
###
POST http://localhost:8080/tips
Content-Type: application/json
Accept: application/json

{
  "nombre_imagen": "tips7",
  "url": "http://img7",
  "veterinario_id": 1,
  "titulo": "Comida saludable",
  "descripcion": "La cascara de verduras es una buena opcion para hacer hervir tus sopitas."
}
###
GET http://localhost:8080/empresapublicidad
###

POST http://localhost:8080/empresapublicidad
Content-Type: application/json
Accept: application/json

{
  "usuario_id": 3,
  "nombre_empresa": "Pets",
  "num_telef": "2222222",
  "email": "pets@gmail.com",
  "tarifa_id": 1,
  "nombre_anuncio": "A la moda",
  "marca_producto": "Dog Fashion"
}
