GET http://localhost:8080/usuario
###
GET http://localhost:8080/usuario/3
###
POST http://localhost:8080/usuario
Content-Type: application/json
Accept: application/json

{
  "nombre_usuarios": "veterinario3",
  "contrasena": "veterinario3"
}

